# Generated by Django 5.0 on 2023-12-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_detailsproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detailsproduct',
        ),
    ]
