# Generated by Django 5.0 on 2023-12-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
